<?php

namespace Database\Seeders;

use App\Models\AmazonBook;
use Illuminate\Database\Seeder;

class AmazonBooksSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'asin'           => '8416918767',
                'title'          => 'Los sabores de México: Recetas tradicionales',
                'author'         => 'Margarita Carrillo Arronte',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/71k9nOQ3MiL._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/8416918767',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/8416918767',
                'amazon_url_es'  => 'https://www.amazon.es/dp/8416918767',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/8416918767',
                'cuisine_type'   => 'mexicana',
                'description'    => 'La biblia definitiva de la cocina mexicana con más de 700 recetas auténticas de todas las regiones del país. Desde moles oaxaqueños hasta ceviches de Veracruz, un recorrido gastronómico completo.',
                'keywords_match' => ['mexicana', 'tacos', 'mole', 'guacamole', 'enchiladas', 'chile', 'tostadas'],
                'sort_order'     => 1,
                'is_active'      => true,
            ],
            [
                'asin'           => '8408274961',
                'title'          => 'Perú: La cocina de mi tierra',
                'author'         => 'Gastón Acurio',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/71A3TvfYBPL._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/8408274961',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/8408274961',
                'amazon_url_es'  => 'https://www.amazon.es/dp/8408274961',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/8408274961',
                'cuisine_type'   => 'peruana',
                'description'    => 'Gastón Acurio, el chef más influyente de Latinoamérica, reúne las recetas más emblemáticas de la gastronomía peruana. Ceviche, lomo saltado, causa limeña y mucho más.',
                'keywords_match' => ['peruana', 'ceviche', 'lomo saltado', 'causa', 'aji amarillo', 'tiradito'],
                'sort_order'     => 2,
                'is_active'      => true,
            ],
            [
                'asin'           => '0307476316',
                'title'          => 'Plenty: Vibrant Vegetable Recipes',
                'author'         => 'Yotam Ottolenghi',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/71pGMxDiKLL._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/0307476316',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/0307476316',
                'amazon_url_es'  => 'https://www.amazon.es/dp/0307476316',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/0307476316',
                'cuisine_type'   => 'mediterránea',
                'description'    => 'El clásico de Ottolenghi que revolucionó la cocina vegetariana con ingredientes mediterráneos y de Oriente Medio. Más de 120 recetas con berenjenas, garbanzos, especias aromáticas y mucho más.',
                'keywords_match' => ['vegetariana', 'mediterránea', 'berenjenas', 'garbanzos', 'especias', 'hummus'],
                'sort_order'     => 3,
                'is_active'      => true,
            ],
            [
                'asin'           => '8408168274',
                'title'          => 'Cocina Española: El recetario fundamental',
                'author'         => 'Karlos Arguiñano',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/61qBTtCkrGL._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/8408168274',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/8408168274',
                'amazon_url_es'  => 'https://www.amazon.es/dp/8408168274',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/8408168274',
                'cuisine_type'   => 'española',
                'description'    => 'Las recetas más queridas de la cocina española de la mano del chef más popular de la televisión. Paella, tortilla, gazpacho, cocido madrileño y todos los clásicos explicados paso a paso.',
                'keywords_match' => ['española', 'paella', 'tortilla', 'gazpacho', 'cocido', 'arroz'],
                'sort_order'     => 4,
                'is_active'      => true,
            ],
            [
                'asin'           => '1984857894',
                'title'          => 'Salt Fat Acid Heat',
                'author'         => 'Samin Nosrat',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/71EeKKLX3iL._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/1984857894',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/1984857894',
                'amazon_url_es'  => 'https://www.amazon.es/dp/1984857894',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/1984857894',
                'cuisine_type'   => 'internacional',
                'description'    => 'El libro de cocina más premiado de los últimos años. Nosrat enseña los 4 elementos fundamentales de cualquier gran plato: sal, grasa, ácido y calor. Una guía que transforma la manera de cocinar.',
                'keywords_match' => ['técnicas', 'sal', 'marinados', 'salsas', 'asados', 'cocina desde cero'],
                'sort_order'     => 5,
                'is_active'      => true,
            ],
            [
                'asin'           => '9874916249',
                'title'          => 'La cocina de Ecuador: Sabores del mundo andino',
                'author'         => 'Julio Pazos Barrera',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/61uNAf0KEFL._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/9874916249',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/9874916249',
                'amazon_url_es'  => 'https://www.amazon.es/dp/9874916249',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/9874916249',
                'cuisine_type'   => 'ecuatoriana',
                'description'    => 'Un viaje culinario por las tres regiones del Ecuador: Costa, Sierra y Amazonía. Seco de pollo, ceviche de camarón, hornado, locro de papa y las recetas más representativas del país.',
                'keywords_match' => ['ecuatoriana', 'seco', 'hornado', 'locro', 'encebollado', 'bolón', 'patacones'],
                'sort_order'     => 6,
                'is_active'      => true,
            ],
            [
                'asin'           => '0553534246',
                'title'          => 'The Joy of Cooking',
                'author'         => 'Irma S. Rombauer',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/81N3fPXpDGL._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/0553534246',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/0553534246',
                'amazon_url_es'  => 'https://www.amazon.es/dp/0553534246',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/0553534246',
                'cuisine_type'   => 'internacional',
                'description'    => 'La enciclopedia de cocina más vendida de todos los tiempos. Más de 4.500 recetas con técnicas detalladas, desde lo básico hasta lo gourmet. Un libro esencial en toda cocina.',
                'keywords_match' => ['técnicas básicas', 'repostería', 'carnes', 'sopas', 'salsas', 'pastas'],
                'sort_order'     => 7,
                'is_active'      => true,
            ],
            [
                'asin'           => '8408203428',
                'title'          => 'Postres: El gran libro de la repostería',
                'author'         => 'Christophe Felder',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/71kMjSJMVzL._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/8408203428',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/8408203428',
                'amazon_url_es'  => 'https://www.amazon.es/dp/8408203428',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/8408203428',
                'cuisine_type'   => 'repostería',
                'description'    => 'La biblia de la repostería francesa. Christophe Felder, uno de los mejores pasteleros del mundo, comparte más de 200 recetas de tartas, pasteles, macarons, helados y chocolates.',
                'keywords_match' => ['repostería', 'pasteles', 'tartas', 'macarons', 'tres leches', 'churros', 'flan', 'postres'],
                'sort_order'     => 8,
                'is_active'      => true,
            ],
            [
                'asin'           => '0385346153',
                'title'          => 'Jerusalem: A Cookbook',
                'author'         => 'Yotam Ottolenghi & Sami Tamimi',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/81jZ3kd5C+L._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/0385346153',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/0385346153',
                'amazon_url_es'  => 'https://www.amazon.es/dp/0385346153',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/0385346153',
                'cuisine_type'   => 'mediterránea',
                'description'    => 'Un viaje a los sabores de Jerusalén con recetas de la cocina árabe, judía y armenia. Falafel, shakshuka, taboulé, hummus y platos con especias que transformarán tu cocina.',
                'keywords_match' => ['mediterránea', 'especias', 'garbanzos', 'berenjenas', 'vegetariana', 'hummus', 'falafel'],
                'sort_order'     => 9,
                'is_active'      => true,
            ],
            [
                'asin'           => '8408165224',
                'title'          => 'Colombia: Cocina de regiones',
                'author'         => 'María Josefa Llano',
                'cover_image_url'=> 'https://m.media-amazon.com/images/I/61S0hM3QKZL._SY466_.jpg',
                'amazon_url_us'  => 'https://www.amazon.com/dp/8408165224',
                'amazon_url_mx'  => 'https://www.amazon.com.mx/dp/8408165224',
                'amazon_url_es'  => 'https://www.amazon.es/dp/8408165224',
                'amazon_url_ar'  => 'https://www.amazon.com.ar/dp/8408165224',
                'cuisine_type'   => 'colombiana',
                'description'    => 'Un recorrido por la diversidad gastronómica colombiana: ajiaco bogotano, bandeja paisa, sancocho costeño, empanadas y los platos más representativos de cada región.',
                'keywords_match' => ['colombiana', 'ajiaco', 'bandeja paisa', 'sancocho', 'empanadas', 'arroz con coco'],
                'sort_order'     => 10,
                'is_active'      => true,
            ],
        ];

        foreach ($books as $book) {
            AmazonBook::updateOrCreate(
                ['asin' => $book['asin']],
                $book
            );
        }

        $this->command->info('✅ 10 libros de Amazon insertados correctamente.');
    }
}
